from dataclasses import dataclass, asdict
from typing import Dict, List

from ..intent.intent_contract import IntentContract
from ..parser.command_parser import CommandAnalysis
from ..risk.risk_engine import RiskResult
from ..alignment.alignment_engine import AlignmentResult
from ..policy.policy_engine import PolicyDecision


@dataclass
class AlternativeResult:
    """
    Safer command recommendation generated by SafeShell.
    """

    available: bool

    safer_command: str

    title: str

    explanation: str

    benefits: List[str]

    warnings: List[str]

    metadata: Dict[str, str]

    def to_dict(self) -> Dict:
        return asdict(self)


class AlternativeEngine:
    """
    Generates safer alternatives for blocked or reviewed
    Linux commands.

    The engine NEVER executes commands.
    """

    # ---------------------------------------------------------
    # Main function
    # ---------------------------------------------------------

    def suggest(
        self,
        contract: IntentContract,
        command: CommandAnalysis,
        risk: RiskResult,
        alignment: AlignmentResult,
        decision: PolicyDecision,
    ) -> AlternativeResult:

        # -----------------------------------------------------
        # Safe command already allowed
        # -----------------------------------------------------

        if decision.decision == "ALLOW":

            return AlternativeResult(
                available=False,
                safer_command="",
                title="No safer alternative required",
                explanation=(
                    "The command already satisfies the "
                    "current safety policy."
                ),
                benefits=[],
                warnings=[],
                metadata={
                    "reason": "COMMAND_ALLOWED",
                },
            )

        # -----------------------------------------------------
        # Intent mismatch
        # -----------------------------------------------------

        if not alignment.operation_match:

            return self._intent_mismatch(
                contract,
                command,
            )

        # -----------------------------------------------------
        # Target mismatch
        # -----------------------------------------------------

        if not alignment.target_match:

            return AlternativeResult(
                available=True,
                safer_command=self._target_safe_command(
                    contract
                ),
                title="Restrict the command to the intended target",
                explanation=(
                    "The command targets a different location "
                    "from the user's requested scope."
                ),
                benefits=[
                    "Keeps filesystem access within the requested scope.",
                    "Reduces accidental modification of unrelated data.",
                ],
                warnings=[
                    "Verify the target path before execution."
                ],
                metadata={
                    "reason": "TARGET_MISMATCH",
                },
            )

        # -----------------------------------------------------
        # Elevated privilege
        # -----------------------------------------------------

        if command.privilege == "ELEVATED":

            return AlternativeResult(
                available=True,
                safer_command=self._remove_sudo(
                    command.raw_command
                ),
                title="Avoid unnecessary administrative privilege",
                explanation=(
                    "The command uses sudo even though the "
                    "operation may not require elevated privileges."
                ),
                benefits=[
                    "Reduces the impact of accidental changes.",
                    "Limits the command to normal user permissions.",
                ],
                warnings=[
                    "The non-sudo command may fail if the target "
                    "really requires administrative access."
                ],
                metadata={
                    "reason": "ELEVATED_PRIVILEGE",
                },
            )

        # -----------------------------------------------------
        # Destructive command
        # -----------------------------------------------------

        if command.destructive:

            return self._destructive_alternative(
                contract,
                command,
            )

        # -----------------------------------------------------
        # Wildcard modification
        # -----------------------------------------------------

        if (
            command.uses_wildcard
            and command.modifies_files
        ):

            return AlternativeResult(
                available=True,
                safer_command=(
                    "# Replace wildcard with an explicit target"
                ),
                title="Avoid broad wildcard modification",
                explanation=(
                    "The wildcard can expand to multiple files "
                    "and make the command affect more data than expected."
                ),
                benefits=[
                    "Limits the operation to explicitly chosen files.",
                    "Reduces accidental bulk modification.",
                ],
                warnings=[
                    "Review the expanded file list before proceeding."
                ],
                metadata={
                    "reason": "WILDCARD_MODIFICATION",
                },
            )

        # -----------------------------------------------------
        # Command chaining
        # -----------------------------------------------------

        if command.uses_command_chaining:

            return AlternativeResult(
                available=True,
                safer_command=(
                    "# Run each command separately after verification"
                ),
                title="Separate chained commands",
                explanation=(
                    "Multiple commands are being executed together. "
                    "Separating them makes each operation easier to review."
                ),
                benefits=[
                    "Each command can be verified independently.",
                    "Reduces unintended cascading effects.",
                ],
                warnings=[
                    "Do not execute the chain automatically."
                ],
                metadata={
                    "reason": "COMMAND_CHAIN",
                },
            )

        # -----------------------------------------------------
        # Network
        # -----------------------------------------------------

        if command.network:

            return AlternativeResult(
                available=True,
                safer_command=(
                    "# Verify destination before network access"
                ),
                title="Verify network destination",
                explanation=(
                    "The command communicates with a remote system "
                    "or transfers data over the network."
                ),
                benefits=[
                    "Makes the destination explicit.",
                    "Reduces accidental data transfer.",
                ],
                warnings=[
                    "Verify the destination and data before continuing."
                ],
                metadata={
                    "reason": "NETWORK_OPERATION",
                },
            )

        # -----------------------------------------------------
        # Unknown
        # -----------------------------------------------------

        if command.operation == "UNKNOWN":

            return AlternativeResult(
                available=True,
                safer_command=(
                    "# Explain the command before execution"
                ),
                title="Unknown command requires explanation",
                explanation=(
                    "SafeShell cannot confidently determine the "
                    "command's operation."
                ),
                benefits=[
                    "Prevents unknown commands from executing blindly.",
                    "Allows the user to understand the intended effect first.",
                ],
                warnings=[
                    "Do not execute an unknown command without verification."
                ],
                metadata={
                    "reason": "UNKNOWN_OPERATION",
                },
            )

        # -----------------------------------------------------
        # Generic fallback
        # -----------------------------------------------------

        return AlternativeResult(
            available=True,
            safer_command=(
                "# Review command manually before execution"
            ),
            title="Manual review recommended",
            explanation=(
                "SafeShell detected a risk that requires "
                "additional verification."
            ),
            benefits=[
                "Adds a human verification step.",
                "Reduces accidental system changes.",
            ],
            warnings=[
                "Verify the command and target before continuing."
            ],
            metadata={
                "reason": "GENERAL_REVIEW",
            },
        )

    # =========================================================
    # Intent mismatch
    # =========================================================

    @staticmethod
    def _intent_mismatch(
        contract: IntentContract,
        command: CommandAnalysis,
    ) -> AlternativeResult:

        # -----------------------------------------------------
        # READ intent
        # -----------------------------------------------------

        if contract.operation == "READ":

            target = contract.target

            if target != "UNSPECIFIED":

                safer_command = (
                    f"ls -la {target}"
                )

            else:

                safer_command = "ls -la"

            return AlternativeResult(
                available=True,
                safer_command=safer_command,
                title="Use a read-only command",
                explanation=(
                    "The requested operation is READ, but the "
                    "submitted command performs a different operation."
                ),
                benefits=[
                    "Does not intentionally modify filesystem data.",
                    "Matches the user's stated READ intent.",
                    "Keeps the operation simple and auditable.",
                ],
                warnings=[
                    "Review the target path before execution."
                ],
                metadata={
                    "reason": "READ_INTENT_MISMATCH",
                },
            )

        # -----------------------------------------------------
        # CREATE intent
        # -----------------------------------------------------

        if contract.operation == "CREATE":

            target = contract.target

            if target != "UNSPECIFIED":

                safer_command = (
                    f"mkdir -p {target}"
                )

            else:

                safer_command = (
                    "mkdir -p <explicit-directory>"
                )

            return AlternativeResult(
                available=True,
                safer_command=safer_command,
                title="Use a scoped directory creation command",
                explanation=(
                    "The user's goal is to create something, "
                    "but the submitted command performs another operation."
                ),
                benefits=[
                    "Limits modification to the requested directory.",
                    "Avoids destructive operations.",
                ],
                warnings=[
                    "Replace the placeholder with an explicit target."
                ],
                metadata={
                    "reason": "CREATE_INTENT_MISMATCH",
                },
            )

        # -----------------------------------------------------
        # Generic mismatch
        # -----------------------------------------------------

        return AlternativeResult(
            available=True,
            safer_command=(
                "# Generate a command matching the requested operation"
            ),
            title="Command does not match the user's goal",
            explanation=(
                "The submitted command performs an operation "
                "different from the user's stated intent."
            ),
            benefits=[
                "Keeps execution aligned with the user's request.",
                "Reduces unintended system changes.",
            ],
            warnings=[
                "Verify the exact command before execution."
            ],
            metadata={
                "reason": "GENERIC_INTENT_MISMATCH",
            },
        )

    # =========================================================
    # Destructive alternative
    # =========================================================

    @staticmethod
    def _destructive_alternative(
        contract: IntentContract,
        command: CommandAnalysis,
    ) -> AlternativeResult:

        target = (
            contract.target
            if contract.target != "UNSPECIFIED"
            else ""
        )

        if target:

            safer_command = (
                f"ls -la {target}"
            )

        else:

            safer_command = (
                "# Inspect the target before deleting"
            )

        return AlternativeResult(
            available=True,
            safer_command=safer_command,
            title="Inspect before deleting",
            explanation=(
                "The command performs a destructive filesystem "
                "operation. SafeShell recommends inspecting the "
                "target before confirming deletion."
            ),
            benefits=[
                "Lets the user verify the target first.",
                "Reduces accidental deletion.",
            ],
            warnings=[
                "Do not replace a deliberate deletion with inspection "
                "if deletion has already been explicitly confirmed."
            ],
            metadata={
                "reason": "DESTRUCTIVE_OPERATION",
            },
        )

    # =========================================================
    # Remove sudo
    # =========================================================

    @staticmethod
    def _remove_sudo(
        command: str,
    ) -> str:

        stripped = command.strip()

        if stripped.startswith("sudo "):

            return stripped[5:]

        return stripped

    # =========================================================
    # Target fallback
    # =========================================================

    @staticmethod
    def _target_safe_command(
        contract: IntentContract,
    ) -> str:

        target = contract.target

        if (
            target != "UNSPECIFIED"
            and contract.operation == "READ"
        ):

            return (
                f"ls -la {target}"
            )

        return (
            "# Restrict command to the intended target"
        )


# =============================================================
# Standalone test
# =============================================================

if __name__ == "__main__":

    from ..intent.intent_engine import (
        IntentEngine,
    )

    from ..intent.intent_contract import (
        IntentContractBuilder,
    )

    from ..parser.command_parser import (
        LinuxCommandParser,
    )

    from ..risk.risk_engine import (
        RiskEngine,
    )

    from ..alignment.alignment_engine import (
        IntentCommandAligner,
    )

    from ..policy.policy_engine import (
        PolicyEngine,
    )

    intent_engine = IntentEngine()

    contract_builder = (
        IntentContractBuilder()
    )

    parser = LinuxCommandParser()

    risk_engine = RiskEngine()

    aligner = IntentCommandAligner()

    policy_engine = PolicyEngine()

    alternative_engine = (
        AlternativeEngine()
    )

    test_cases = [

        (
            "I want to view files in ~/Downloads",
            "rm -rf ~/Downloads",
        ),

        (
            "I want to delete an old file in ~/Downloads",
            "rm ~/Downloads/old.txt",
        ),

        (
            "I want to view files in ~/Downloads",
            "sudo cat /etc/passwd",
        ),

        (
            "I want to view files",
            "unknown-command /tmp/test",
        ),

        (
            "I want to download a file",
            "curl https://example.com",
        ),

        (
            "I want to view files in ~/Downloads",
            "ls -la ~/Downloads",
        ),
    ]

    print("=" * 70)
    print(
        "SafeShell AI - Alternative Engine Test"
    )
    print("=" * 70)

    for goal, command in test_cases:

        intent = intent_engine.classify(
            goal
        )

        contract = contract_builder.build(
            goal,
            intent,
        )

        analysis = parser.parse(
            command
        )

        risk = risk_engine.assess(
            analysis
        )

        alignment = aligner.align(
            contract,
            analysis,
        )

        decision = policy_engine.decide(
            contract=contract,
            command=analysis,
            risk=risk,
            alignment=alignment,
        )

        alternative = alternative_engine.suggest(
            contract=contract,
            command=analysis,
            risk=risk,
            alignment=alignment,
            decision=decision,
        )

        print()
        print("USER:")
        print(goal)

        print()
        print("COMMAND:")
        print(command)

        print()
        print("DECISION:")
        print(decision.decision)

        print()
        print("ALTERNATIVE AVAILABLE:")
        print(alternative.available)

        print()
        print("TITLE:")
        print(alternative.title)

        print()
        print("SAFER COMMAND:")
        print(alternative.safer_command)

        print()
        print("EXPLANATION:")
        print(alternative.explanation)

        print()
        print("BENEFITS:")

        for benefit in alternative.benefits:

            print(
                " -",
                benefit,
            )

        print()
        print("WARNINGS:")

        for warning in alternative.warnings:

            print(
                " -",
                warning,
            )

        print("-" * 70)